---
  - name: Generate firewall-mangle-{{inventory_hostname}}.rsc to check and add user
    template: src=mangle.rsc.j2 dest={{role_path}}/files/tmp/firewall-mangle-{{inventory_hostname}}.rsc
    delegate_to: localhost

  - name: Send firewall-mangle-{{inventory_hostname}}.rsc script
    command: scp -P {{ansible_port}} {{role_path}}/files/tmp/firewall-mangle-{{inventory_hostname}}.rsc {{ansible_user}}@{{inventory_hostname}}:/firewall-mangle-{{inventory_hostname}}.rsc
    delegate_to: localhost

  - name: Delete temporary firewall-mangle-{{inventory_hostname}}.rsc file
    file: path={{role_path}}/files/tmp/firewall-mangle-{{inventory_hostname}}.rsc state=absent
    delegate_to: localhost

  - name: Run firewall-mangle-{{inventory_hostname}}.rsc on router
    raw:  "/import firewall-mangle-{{inventory_hostname}}.rsc"
    tags: mikrotik_firewall_services

  - name: Remove firewall-mangle-{{inventory_hostname}}.rsc from router
    raw:  "/file remove firewall-mangle-{{inventory_hostname}}.rsc"
